name: Scrape and update leaderboard

on:
  schedule:
    - cron: '30 16 * * *'  # 10:30 AM CST daily
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scrape script
        run: python scraper.py

      - name: Commit and push if it changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data.csv
          git diff --cached --quiet || git commit -m "Update leaderboard data"
          git push
