name: Scrape and update leaderboards

on:
  schedule:
    - cron: '30 14 * * *'  # 8:30 AM CST daily
  workflow_dispatch:

jobs:
  scrape-hitters:
    name: Scrape Hitters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run hitter scraper
        run: |
          mkdir -p data/hitters
          python scraper.py
          mv leaderboard_data.csv data/hitters/
          mv scrape_errors.csv data/hitters/
          mv full_season_data.csv data/hitters/

      - name: Commit and push hitter data
        env:
          GH_TOKEN: ${{ secrets.MILB_LEADERBOARD }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/hitters/*
          git diff --cached --quiet || git commit -m "Update hitter leaderboard data"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git pull --rebase origin main
          git push origin HEAD:main

  scrape-pitchers:
    name: Scrape Pitchers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pitcher scraper
        run: |
          mkdir -p data/pitchers
          python pitch_scraper.py
          mv leaderboard_pitch_data.csv data/pitchers/
          mv scrape_errors_pitch.csv data/pitchers/
          mv full_season_pitch_data.csv data/pitchers/

      - name: Upload output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: leaderboard-pitch-csv
          path: leaderboard_pitch_data.csv

      - name: Commit and push pitcher data
        env:
          GH_TOKEN: ${{ secrets.MILB_LEADERBOARD }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/pitchers/*
          git diff --cached --quiet || git commit -m "Update pitcher leaderboard data"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git pull --rebase origin main
          git push origin HEAD:main


